name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+\\+[0-9]+"

jobs:
  build:
    uses: ./.github/workflows/go.yml

  set-release-info:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      SKIP_RELEASE: ${{ steps.assemble-release-info.outputs.SKIP_RELEASE }}
      RELEASE_VERSION: ${{ steps.assemble-release-info.outputs.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Assemble release info
        id: assemble-release-info
        run: |
          set -vx
          . .github/workflows/release_info.sh ${{ github.event.repository.full_name }} 
          echo CHANGELOG=$(echo -e "${CHANGELOG}") >> $GITHUB_ENV
          echo IS_CANDIDATE=${IS_CANDIDATE} >> $GITHUB_ENV
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
          echo "SKIP_RELEASE=${SKIP_RELEASE}" >> $GITHUB_OUTPUT

  docker:
    if: needs.set-release-info.outputs.SKIP_RELEASE == 'false'
    needs: set-release-info
    uses: ./.github/workflows/docker-push.yml
    with:
      RELEASE_VERSION: ${{ needs.set-release-info.outputs.RELEASE_VERSION }}